- name: Transpose rows and columns
  hosts: localhost
  gather_facts: false
  vars:
    data:
      - [1, 2, 5]
      - [4, 6, 3]
      - [7, 8, 9]

  tasks:
    - name: Transpose rows and columns
      set_fact:
        transposed_data: "{{ data | zip_longest | list }}"
      vars:
        # Importing the filter plugin
        zip_longest: "{{ lookup('pipe', 'python3 -c \"from itertools import zip_longest; import sys; sys.stdout.write(','.join(map(str, [list(x) for x in zip_longest(*map(list, sys.stdin.read().strip().split('\n')))])))\"') | from_yaml }}"
      
    - debug:
        var: transposed_data
